baseURL = 'https://quantumf0am.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site With Docsy!'

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

#adding a link to an external site.
[[menu.main]]
  name = "Repo"
  weight = 100
  url = "https://github.com/quantumf0am/quantumf0am.github.io"
  pre = "<i class='fab fa-github'></i>"
  #post = "<span class='alert'>New!</span>" #adds a 'new' tag to this icon

[params]
  github_repo = "https://github.com/quantumf0am/quantumf0am.github.io"

[params.ui]
  #disable the 'about' in the footer
  footer_about_disable = true